// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Petstagram.Context;

#nullable disable

namespace Petstagram.Migrations
{
    [DbContext(typeof(PetContext))]
    partial class PetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetPicture", b =>
                {
                    b.Property<int>("PetsId")
                        .HasColumnType("int");

                    b.Property<int>("PicturesId")
                        .HasColumnType("int");

                    b.HasKey("PetsId", "PicturesId");

                    b.HasIndex("PicturesId");

                    b.ToTable("PetPicture", (string)null);

                    b.HasData(
                        new
                        {
                            PetsId = 2,
                            PicturesId = 1
                        },
                        new
                        {
                            PetsId = 2,
                            PicturesId = 2
                        },
                        new
                        {
                            PetsId = 2,
                            PicturesId = 3
                        },
                        new
                        {
                            PetsId = 2,
                            PicturesId = 4
                        },
                        new
                        {
                            PetsId = 2,
                            PicturesId = 5
                        },
                        new
                        {
                            PetsId = 3,
                            PicturesId = 6
                        },
                        new
                        {
                            PetsId = 3,
                            PicturesId = 7
                        },
                        new
                        {
                            PetsId = 3,
                            PicturesId = 8
                        },
                        new
                        {
                            PetsId = 3,
                            PicturesId = 9
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 10
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 11
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 12
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 13
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 14
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 15
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 16
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 17
                        },
                        new
                        {
                            PetsId = 1,
                            PicturesId = 18
                        });
                });

            modelBuilder.Entity("Petstagram.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diddy",
                            OwnerId = "Demo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Balto",
                            OwnerId = "Demo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cat",
                            OwnerId = "Demo"
                        });
                });

            modelBuilder.Entity("Petstagram.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "A New Beginning",
                            FileName = "balto (1).jpg",
                            LastModified = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Balto looks back to the town he helped save with the medicine he brought back to save a small girls life. The townsfolk have finally accepted him, he is now the sled dog's leader, and he has won the heart of the love of his life. Things are finally starting to look up for him.",
                            UploadDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Perilous Journey",
                            FileName = "balto (2).jpg",
                            LastModified = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Balto looks to the journey ahead, realizing it is not going to be an easy one. However, he is determined to deliver the medicine so that his love's owner can live. A storm is snow storm is coming, and the clock is ticking. Will he be able to make it in ti me?",
                            UploadDate = new DateTime(2022, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Unexpected Meeting",
                            FileName = "balto (3).jpg",
                            LastModified = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "This is when Balto first met the love of his life, Jenna. Balto decided to join in a dog race being held in town and beat all the other sled dogs. However because the wown saw he was a wolf dog they shunned him and tried to run him out of town. In his escape he ran into Jenna and thus, a new love story was born.",
                            UploadDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Real Life Legend",
                            FileName = "balto (4).jpg",
                            LastModified = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Balto is actually real, there is a statue dedicated to his heroics in Central Park, Manhattan. It is made of bronze by Frederick Roth. The plague at the base reads &quot;Dedicated tot he indomitable spirit of the sled dogs that relayed antitoxin six hundred miles over rough ice, across treacherous waters, through Artic blizzards from Nenana to the relief of stricken Nome in the Winter of 1925. Endurance · Fidelity · Intelligence&quot;",
                            UploadDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Never Ending Friendship",
                            FileName = "balto (5).jpg",
                            LastModified = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Back when Balto was an outcast, his best friend and Father figure is this snow goose named Boris. They lived together in an abandoned boat outside of town. He is usually the one Balto turns to when he needs advice. He does his best to support Balto, and even became Uncle to his puppies.",
                            UploadDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Wandering Around",
                            FileName = "cat (1).jpg",
                            LastModified = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Under the warm glow of the setting sun, an orange feline gracefully wanders through the vast expanse of a rural farm. Its fur, the color of autumn leaves, catches the last light as it meanders among the fields of swaying wheat. With each step, the cat's keen eyes survey the landscape, tracing the intricate patterns of the earth. Whiskers twitching with curiosity, it explores every corner of the farm, blending seamlessly with the rustic backdrop of old barns and green pastures. Pausing atop a weathered fence post, the feline gazes out over its domain, a silent ruler of the tranquil countryside.",
                            UploadDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Deserved Rest",
                            FileName = "cat (2).jpg",
                            LastModified = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "In the soft glow of daylight filtering through the windows, an orange cat cozies up on a sun-drenched patch of the living room floor, seeking refuge from the hustle and bustle of the outside world. With eyes gently closed, it succumbs to the allure of a midday siesta, the warmth of the sun's rays wrapping it in a comforting embrace. As the minutes tick by, the cat's rhythmic purrs harmonize with the quiet hum of the household, a gentle lullaby that soothes both body and soul. In this tranquil moment, it is a picture of pure contentment, nestled within the safety and warmth of its indoor sanctuary.",
                            UploadDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Fear Him",
                            FileName = "cat (3).jpg",
                            LastModified = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "As dawn breaks, the orange cat rouses from its slumber, shooting you a disgruntled look. Though still nestled in comfort, its eyes convey annoyance at the interruption. With a deliberate stretch and a reproachful stare, it silently demands restitution for the disturbance before settling back into its cozy cocoon, a silent reminder to tread lightly in its realm of rest.",
                            UploadDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "He Prowls Again",
                            FileName = "cat (4).jpg",
                            LastModified = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Story = "Beneath the afternoon sun, the orange cat prowls the backyard, eyes fixed on the grass. With a sudden burst of energy, it pounces, emerging victorious with a small bird in its jaws. With a triumphant glance, it disappears into the shadows, leaving behind the rustle of grass in its wake.",
                            UploadDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "Base Form Diddy",
                            FileName = "diddy (1).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9802),
                            Story = "Meet Diddy, the cute brown Chihuahua mix with a heart of gold. Despite his small size, Diddy is bursting with personality and charm. With his expressive eyes and perky ears, he's always ready to steal your heart with just a wag of his tail. Diddy loves cuddling in your lap and chasing his favorite toys with boundless energy. Fearless and affectionate, he brightens every day with his playful antics and unwavering loyalty. Life is simply better with Diddy around.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9748)
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "Stare of Diddy",
                            FileName = "diddy (2).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9807),
                            Story = "Diddy, the adorable brown Chihuahua mix, may be small, but his stare is as serious as they come. With furrowed brows and intense eyes, he fixes his gaze on whatever captures his attention, be it a passing squirrel or a distant sound. In those moments, there's no mistaking his focus and determination. It's as if he's pondering life's deepest mysteries or standing guard over his beloved humans. Despite his playful nature, Diddy's serious stare reminds you that even the smallest of dogs can possess a big dose of gravitas.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9805)
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Stare of Diddy",
                            FileName = "diddy (3).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9811),
                            Story = "Imagine Diddy, the suave brown Chihuahua mix, sporting a pair of trendy glasses and a snazzy tie, exuding an air of effortless coolness. With his glasses perched just right and his tie impeccably knotted, he struts down the street, turning heads with his confident swagger. Diddy's cool demeanor is infectious, and he knows it, flashing a charming grin as he captures the attention of everyone he passes. Whether he's lounging in a cafe or basking in the sun at the park, Diddy's undeniable style and laid-back attitude make him the epitome of cool canine charm.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9809)
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Doge of War",
                            FileName = "diddy (4).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9815),
                            Story = "Diddy, the once cheerful brown Chihuahua mix, now bears the anger of Kratos, the god of war. His playful demeanor replaced by a fierce snarl, and his innocent gaze now burns with the intensity of ancient wrath. With each step, his paws echo the thunderous march of a warrior, and his every growl reverberates with the might of a deity. No longer content with simple games, Diddy prowls with the ferocity of a god in battle, his tiny frame a vessel for divine rage. Those who once knew him tremble in fear at the sight of his transformed form, for Diddy, now imbued with the wrath of Kratos, commands the respect and awe of mortals and gods alike.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9813)
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Legendary Super Doge",
                            FileName = "diddy (5).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9819),
                            Story = "Pushed to his limits, Diddy stood amidst the chaos of battle, his determination unwavering despite the odds stacked against him. As the clash intensified, a surge of energy enveloped him, filling him with an unprecedented power. With a mighty roar, he unleashed his latent strength, his fur glowing with a radiant aura. In that moment of sheer willpower, Diddy transcended his canine form, ascending to the ranks of the legendary super saiyan. With newfound power coursing through his veins, he soared into the fray, his bark echoing with the force of a thousand warriors as he faced his adversaries head-on, ready to defend his world at any cost.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9817)
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Mythical Beast Diddy",
                            FileName = "diddy (6).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9823),
                            Story = "In the realm of mystic wonders, Diddy stands tall as the mighty dog of magic. With a flick of his tail and a glint in his eye, he commands the very forces of enchantment. His fur glistens with the shimmer of ancient spells, and his bark echoes with the power of incantations long forgotten. As he roams through realms of mystical beauty, Diddy's presence sparks awe and wonder among all who behold him. With each step, he reaffirms his role as the guardian of magic, ensuring that its secrets remain safe and its wonders never fade.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9821)
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "Determination",
                            FileName = "diddy (7).png",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9827),
                            Story = "With unwavering resolve, Diddy stands tall, his eyes burning with determination. Despite the challenges that lay ahead, he remains steadfast in his pursuit of his goals. With each step forward, he channels his inner strength, ready to overcome any obstacle in his path. No setback can deter him, for his spirit is unbreakable and his will indomitable. With a heart full of courage and a mind set on success, Diddy presses on, confident in his ability to achieve greatness.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9826)
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "Xmas Miracle",
                            FileName = "diddy (8).jpg",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9831),
                            Story = "In the heart of the North Pole, amidst the swirling snowflakes and twinkling lights, Santa Diddy reigns as the beloved canine companion of the holiday season. With his red coat trimmed in white fur and a jolly twinkle in his eye, he spreads cheer and goodwill to all he meets. From his sleigh pulled by a team of spirited reindeer to his jolly laugh that echoes through the frosty air, Santa Diddy embodies the magic of Christmas. With a wag of his tail and a hearty &quot;Ho, ho, ho&quot; he delivers joy to homes around the world, ensuring that the spirit of the season shines bright for all.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9830)
                        },
                        new
                        {
                            Id = 18,
                            DisplayName = "Rest Friend",
                            FileName = "diddy (9).jpg",
                            LastModified = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9835),
                            Story = "As the day draws to a close, Diddy finds solace in the soft embrace of his favorite spot—the bed. With a contented sigh, he curls up amidst the cozy blankets, his eyes heavy with the weight of the day's adventures. As he nestles into the warmth, a sense of tranquility washes over him, melting away the cares of the world. With each gentle breath, he sinks deeper into relaxation, the rhythmic rise and fall of his chest a soothing lullaby. In this moment of peaceful serenity, Diddy finds respite from the chaos of the day, basking in the simple joy of rest and relaxation.",
                            UploadDate = new DateTime(2025, 4, 8, 16, 59, 3, 280, DateTimeKind.Local).AddTicks(9834)
                        });
                });

            modelBuilder.Entity("Petstagram.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Petstagram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Petstagram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Petstagram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Petstagram.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetPicture", b =>
                {
                    b.HasOne("Petstagram.Models.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Petstagram.Models.Picture", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
